import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "../providers";
import { NavBar } from "@/components/NavBar";
import { createClient } from "@/utils/supabase/server";
import { redirect } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Supabase Auth for users
  const supabase = await createClient();

  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/login");
  }

  return (
    // Suppress as client and server side may not match due to use of next-themes
    <Providers>
      <NavBar />
      {children}
      <Toaster />
    </Providers>
  );
}
