import type { Metadata } from "next";
import "../globals.css";
import { Providers } from "../providers";
import { NavBar } from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Suppress as client and server side may not match due to use of next-themes
    <Providers>
      <NavBar />
      {children}
    </Providers>
  );
}
